import { createTheme } from '@nextui-org/react'

export const lightTheme = createTheme({
  type: 'light',
  theme: {
    colors: {
      primaryLight: '$blue200',
      primaryLightHover: '$blue300',
      primaryLightActive: '$blue400',
      primaryLightContrast: '$blue600',
      primary: '$blue700',
      primaryBorder: '$blue500',
      primaryBorderHover: '$blue600',
      primarySolidHover: '$blue700',
      primarySolidContrast: '$white',
      primaryShadow: '$blue500',
      secondaryLight: '$gray200',
      secondaryLightHover: '$gray300',
      secondaryLightActive: '$gray400',
      secondaryLightContrast: '$gray600',
      secondary: '$gray600',
      secondaryBorder: '$gray500',
      secondaryBorderHover: '$gray600',
      secondarySolidHover: '$gray700',
      secondarySolidContrast: '$white',
      secondaryShadow: '$gray500',
      code: '$blue700',
      codeLight: '#fafafa',
    },
    space: {},
    fonts: {},
  },
})

export const darkTheme = createTheme({
  type: 'dark',
  theme: {
    colors: {
      primaryLight: '$blue200',
      primaryLightHover: '$blue300',
      primaryLightActive: '$blue400',
      primaryLightContrast: '$blue600',
      primary: '$blue700',
      primaryBorder: '$blue500',
      primaryBorderHover: '$blue600',
      primarySolidHover: '$blue700',
      primarySolidContrast: '$white',
      primaryShadow: '$blue500',
      secondaryLight: '$gray200',
      secondaryLightHover: '$gray300',
      secondaryLightActive: '$gray400',
      secondaryLightContrast: '$gray600',
      secondary: '$gray600',
      secondaryBorder: '$gray500',
      secondaryBorderHover: '$gray600',
      secondarySolidHover: '$gray700',
      secondarySolidContrast: '$white',
      secondaryShadow: '$gray500',
      code: '$blue700',
      codeLight: '#282C34',
    },
    space: {},
    fonts: {},
  },
})
